version: '3.9'

services:
  web:
    container_name: risegen_web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma_data/prod.db
      - NEXTAUTH_SECRET=changeme_secret
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      # Persist SQLite Database - Mounting to a separate data directory to avoid overwriting application code (schema.prisma)
      - ./prisma_data:/app/prisma_data
      # Persist Uploaded Files
      - ./uploads:/app/public/uploads
